
name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          # this is what I use on my system. I cannot guarantee any other version works
          sdk-version: 20348

      - name: Set up JDK versions
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup the workspace
        run: ./gradlew --build-cache --info --stacktrace setupCIWorkspace

      - name: Compile the mod
        run: ./gradlew --build-cache --info --stacktrace assemble

      - name: Attach compilation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_id }}-build-libs
          path: build/libs
          retention-days: 31

      - name: Run post-build checks
        id: build_mod
        run: ./gradlew --build-cache --info --stacktrace build

      - name: Attach gradle reports
        if: failure() && steps.build_mod.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ github.repository_id }}-reports
          path: build/reports/
          retention-days: 31
